name: wtc_wallet_app
version: 1.0.6+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bip39: ^1.0.6
  crypt: ^4.2.1
  cupertino_icons: ^1.0.2
  ed25519_hd_key: ^2.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.3
  flutter_inappwebview: ^5.3.2
  flutter_linkify: ^5.0.2
  get: ^4.6.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  ota_update: ^4.0.1
  package_info_plus: ^1.4.2
  qr_flutter: ^4.0.0
  scan: ^1.6.0
  url_launcher: ^6.0.20
  web3dart: ^2.3.5

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/files/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
